"""update models

Revision ID: 05851b8a6ba2
Revises: ba0b30c2d211
Create Date: 2026-02-27 10:35:56.410845

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "05851b8a6ba2"
down_revision: Union[str, Sequence[str], None] = "ba0b30c2d211"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column(
    #     "received_invoices",
    #     sa.Column("original_invoice_id", sa.Integer(), nullable=True),
    # )
    # op.create_foreign_key(
    #     None, "received_invoices", "invoices", ["original_invoice_id"], ["id"]
    # )
    # op.drop_column('received_invoices', 'pr_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('received_invoices', sa.Column('pr_number', sa.VARCHAR(), nullable=True))
    # op.drop_constraint(None, "received_invoices", type_="foreignkey")
    # op.drop_column("received_invoices", "original_invoice_id")
    # ### end Alembic commands ###
