"""make invoice completed after last payment

Revision ID: 0bd7f2efc994
Revises: 0499bb751a07
Create Date: 2026-03-05 10:41:36.347453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd7f2efc994'
down_revision: Union[str, Sequence[str], None] = '0499bb751a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('completed_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'completed_date')
    # ### end Alembic commands ###
