"""make po_number indexable

Revision ID: 0eee9606b193
Revises: 72f48d68a8d0
Create Date: 2026-02-23 09:21:53.394603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eee9606b193'
down_revision: Union[str, Sequence[str], None] = '72f48d68a8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_invoices_po_number'), 'invoices', ['po_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_po_number'), table_name='invoices')
    # ### end Alembic commands ###
