"""add assigned and proccessed invoices to user

Revision ID: 1b55ee2f5d80
Revises: 73a8151150e4
Create Date: 2026-02-17 10:22:22.439794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b55ee2f5d80'
down_revision: Union[str, Sequence[str], None] = '73a8151150e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
