"""add description to received invoice model

Revision ID: 645c579cb4b4
Revises: 10b2e42a17e5
Create Date: 2026-03-02 12:11:23.152881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645c579cb4b4'
down_revision: Union[str, Sequence[str], None] = '10b2e42a17e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('received_invoices', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('received_invoices', 'description')
    # ### end Alembic commands ###
