"""add updated_at to timed model

Revision ID: 64735aaefad3
Revises: 7447c0a5e888
Create Date: 2026-02-20 09:40:26.676998

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision: str = "64735aaefad3"
down_revision: Union[str, Sequence[str], None] = "7447c0a5e888"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


dt = datetime.datetime.now()


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column(
    #     "attachments",
    #     sa.Column(
    #         "updated_at",
    #         sa.DateTime(),
    #         nullable=True,
    #         server_default=str(dt),
    #     ),
    # )
    # op.add_column(
    #     "invoices",
    #     sa.Column(
    #         "updated_at",
    #         sa.DateTime(),
    #         nullable=True,
    #         server_default=str(dt),
    #     ),
    # )
    # op.add_column(
    #     "received_invoices", sa.Column("invoice_id", sa.Integer(), nullable=True)
    # )
    # op.add_column(
    #     "received_invoices", sa.Column("pr_number", sa.String(), nullable=True)
    # )
    # op.add_column(
    #     "received_invoices", sa.Column("po_number", sa.String(), nullable=True)
    # )
    # op.add_column(
    #     "received_invoices", sa.Column("receipt_id", sa.String(), nullable=True)
    # )
    # op.add_column(
    #     "received_invoices",
    #     sa.Column(
    #         "received_by_id",
    #         sa.Integer(),
    #         nullable=True,
    #         server_default=str(dt),
    #     ),
    # )
    # op.add_column(
    #     "received_invoices",
    #     sa.Column(
    #         "updated_at",
    #         sa.DateTime(),
    #         nullable=True,
    #         server_default=str(dt),
    #     ),
    # )
    # op.create_foreign_key(
    #     None, "received_invoices", "users", ["received_by_id"], ["id"]
    # )
    # op.add_column(
    #     "users",
    #     sa.Column(
    #         "updated_at",
    #         sa.DateTime(),
    #         nullable=True,
    #         server_default=str(dt),
    #     ),
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_constraint(None, "received_invoices", type_="foreignkey")
    op.drop_column("received_invoices", "updated_at")
    op.drop_column("received_invoices", "received_by_id")
    op.drop_column("received_invoices", "receipt_id")
    op.drop_column("received_invoices", "po_number")
    op.drop_column("received_invoices", "pr_number")
    op.drop_column("received_invoices", "invoice_id")
    op.drop_column("invoices", "updated_at")
    op.drop_column("attachments", "updated_at")
    # ### end Alembic commands ###
