"""add currency

Revision ID: 6a11e6f3050d
Revises: 0bd7f2efc994
Create Date: 2026-03-05 10:52:00.335825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a11e6f3050d'
down_revision: Union[str, Sequence[str], None] = '0bd7f2efc994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('received_invoices', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('received_invoices', 'currency')
    # ### end Alembic commands ###
