"""add assigned_to and proccessed_by to invoice

Revision ID: 6e3795a14118
Revises: d3524e60d801
Create Date: 2026-02-17 09:56:13.066438

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision: str = "6e3795a14118"
down_revision: Union[str, Sequence[str], None] = "d3524e60d801"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    #
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = [c["name"] for c in inspector.get_columns("invoices")]

    if "assigned_user_id" not in columns:
        op.add_column(
            "invoices",
            sa.Column(
                "assigned_user_id", sa.Integer(), nullable=True, server_default="1"
            ),
        )

    if "processed_by_id" not in columns:
        op.add_column(
            "invoices",
            sa.Column(
                "processed_by_id", sa.Integer(), nullable=True, server_default="1"
            ),
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "invoices", type_="foreignkey")
    op.drop_constraint(None, "invoices", type_="foreignkey")
    op.drop_column("invoices", "processed_by_id")
    op.drop_column("invoices", "assigned_user_id")
    # ### end Alembic commands ###
