"""add status to invoice

Revision ID: 7447c0a5e888
Revises: 1b55ee2f5d80
Create Date: 2026-02-19 14:54:17.237791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7447c0a5e888'
down_revision: Union[str, Sequence[str], None] = '1b55ee2f5d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('status', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'status')
    # ### end Alembic commands ###
