"""add pr and po dates to invoice model

Revision ID: 834001cd5509
Revises: 645c579cb4b4
Create Date: 2026-03-02 13:54:55.579048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834001cd5509'
down_revision: Union[str, Sequence[str], None] = '645c579cb4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('pr_date', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('po_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'po_date')
    op.drop_column('invoices', 'pr_date')
    # ### end Alembic commands ###
