"""update invoice model

Revision ID: b55284c0710f
Revises: e05ec916e0ac
Create Date: 2026-02-10 15:56:22.362041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55284c0710f'
down_revision: Union[str, Sequence[str], None] = 'e05ec916e0ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('processed_by', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'users', ['processed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'processed_at')
    op.drop_column('invoices', 'processed_by')
    # ### end Alembic commands ###
