"""add receipt to invoice model

Revision ID: ba0b30c2d211
Revises: 0eee9606b193
Create Date: 2026-02-23 15:02:01.817239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0b30c2d211'
down_revision: Union[str, Sequence[str], None] = '0eee9606b193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('receipt_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'receipt_id')
    # ### end Alembic commands ###
