"""update models

Revision ID: bb011ea7b331
Revises: e4520f152b18
Create Date: 2026-02-14 11:29:21.691310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb011ea7b331'
down_revision: Union[str, Sequence[str], None] = 'e4520f152b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('vendor', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'vendor')
    # ### end Alembic commands ###
