"""add po and pr numbers

Revision ID: d3524e60d801
Revises: bb011ea7b331
Create Date: 2026-02-14 12:10:46.178287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3524e60d801'
down_revision: Union[str, Sequence[str], None] = 'bb011ea7b331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('po_number', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('pr_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'pr_number')
    op.drop_column('invoices', 'po_number')
    # ### end Alembic commands ###
