"""add currency to invoice model

Revision ID: e05ec916e0ac
Revises: 538fb24a821e
Create Date: 2026-02-10 14:35:32.664432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05ec916e0ac'
down_revision: Union[str, Sequence[str], None] = '538fb24a821e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('currency', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'currency')
    # ### end Alembic commands ###
