import React from "react";
import {
  CheckCircle2,
  Clock,
  Calendar,
  FileText,
  ShoppingCart,
  Receipt,
  CheckCircle,
} from "lucide-react";

const InvoiceTimeline = ({
  timeline = {
    created_at: "",
    pr_date: "",
    po_date: "",
    received_date: "",
    completed_at: "",
  },
}) => {
  // Mapping labels and icons to the data keys
  const steps = [
    {
      id: "created_at",
      label: "Quotation Created",
      icon: FileText,
      description: "Initial quote generated by vendor",
    },
    {
      id: "pr_date",
      label: "Purchase Request (PR)",
      icon: Clock,
      description: "Internal approval requested",
    },
    {
      id: "po_date",
      label: "Purchase Order (PO)",
      icon: ShoppingCart,
      description: "Order officially placed",
    },
    {
      id: "received_date",
      label: "Invoice Received",
      icon: Receipt,
      description: "Bill received from vendor",
    },
    {
      id: "completed_at",
      label: "Process Completed",
      icon: CheckCircle,
      description: "Payment cleared and closed",
    },
  ];

  const formatDate = (dateString) => {
    if (!dateString) return null;
    return new Date(dateString).toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  };

  return (
    <div className="max-w-sm mx-auto bg-white rounded-tr-2xl rounded-br-2xl shadow-md  overflow-hidden">
      <div className="bg-slate-50 border-b border-slate-200 p-6">
        <h2 className="text-xl font-bold text-slate-800">Invoice Tracking</h2>
        <p className="text-sm text-slate-500 mt-1">
          Status of procurement lifecycle
        </p>
      </div>

      <div className="p-8">
        <div className="relative">
          {steps.map((step, index) => {
            const dateValue = timeline[step.id];
            const isCompleted = !!dateValue;
            const isLast = index === steps.length - 1;
            const StepIcon = step.icon;

            const nextStepIsCompleted =
              !isLast && !!timeline[steps[index + 1].id];

            return (
              <div key={step.id} className="group relative flex gap-6">
                <div className="flex flex-col items-center">
                  <div
                    className={`
                      relative z-10 flex h-10 w-10 shrink-0 items-center justify-center rounded-full border-2 transition-all duration-500
                      ${
                        isCompleted
                          ? "bg-teal-600 border-teal-600 shadow-md shadow-teal-100"
                          : "bg-white border-slate-200"
                      }
                    `}
                  >
                    {isCompleted ? (
                      <CheckCircle2 className="h-5 w-5 text-white" />
                    ) : (
                      <div className="h-2 w-2 rounded-full bg-slate-300" />
                    )}
                  </div>

                  {!isLast && (
                    <div
                      className={`
                        w-0.5 grow transition-all duration-500
                        ${nextStepIsCompleted ? "bg-teal-600" : "bg-slate-100"}
                      `}
                      style={{ minHeight: "3rem" }}
                    />
                  )}
                </div>

                <div className={`pb-10 ${isLast ? "pb-0" : ""}`}>
                  <div className="flex flex-col">
                    <span
                      className={`text-sm font-semibold transition-colors duration-300 ${isCompleted ? "text-slate-900" : "text-slate-400"}`}
                    >
                      {step.label}
                    </span>

                    {isCompleted ? (
                      <div className="mt-1 flex items-center gap-2 text-teal-600 font-medium text-xs">
                        <Calendar className="h-3 w-3" />
                        {formatDate(dateValue)}
                      </div>
                    ) : (
                      <span className="mt-1 text-xs text-slate-400 italic">
                        Waiting for action...
                      </span>
                    )}

                    <p className="mt-2 text-xs text-slate-500 leading-relaxed max-w-60">
                      {step.description}
                    </p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default InvoiceTimeline;
